// Generated by `pnpm --filter @packages/auth auth:generate`, then edited.
//
// Regenerating overwrites this file and undoes those edits. Three things have
// to be redone — and all three are caught for you, so you will not have to
// remember them, only fix what the tooling reports:
//
//   1. `pgTable(` becomes `pgTable.withRLS(`. Caught by `rls-guard.test.ts`.
//   2. The `relations(...)` exports at the bottom are deleted. Better Auth's
//      CLI emits Drizzle v0's relations API, which v1 replaced with
//      `defineRelations`. Nothing here uses relational queries — the adapter
//      only reaches for them behind `experimental: { joins: true }`, which
//      this repo forbids — so they are dead weight, not a missing feature.
//      Caught by `tsc`: "'drizzle-orm' has no exported member named
//      'relations'".
//   3. Run `pnpm format`. The generator emits semicolons. Caught by
//      `pnpm format:check`.
//
// Nothing below is business logic. Adding a Better Auth plugin changes what
// the generator emits, so extend by regenerating rather than by hand.

import { boolean, index, pgTable, text, timestamp } from "drizzle-orm/pg-core"

export const user = pgTable.withRLS("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
})

export const session = pgTable.withRLS(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)]
)

export const account = pgTable.withRLS(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)]
)

export const verification = pgTable.withRLS(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)]
)
